language:
    - minimal
  
  install:
    - docker pull nikitastetskiy/micro-calendario
    - docker images
  
  script: 
    - docker run -t -v  $TRAVIS_BUILD_DIR:/test nikitastetskiy/micro-calendario 